spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Samuell0003/news-config-repo



server:
  port: 8888